FROM postgres:17

# Install OpenSSL and sudo
RUN apt-get update && apt-get install -y \
    openssl \
    sudo \
    --no-install-recommends \
    postgresql-contrib \
    pgbouncer postgresql-common \
    lz4 libpq-dev libpq5 pg-activity \
    lsof htop \
    postgresql-17-pgvector \
    postgresql-17-postgis \
    && rm -rf /var/lib/apt/lists/*


# Allow the postgres user to execute certain commands as root without a password
RUN echo "postgres ALL=(root) NOPASSWD: /usr/bin/mkdir, /bin/chown, /usr/bin/openssl" > /etc/sudoers.d/postgres

# Add init scripts while setting permissions
COPY --chmod=755 init-ssl.sh /docker-entrypoint-initdb.d/init-ssl.sh
COPY --chmod=755 wrapper.sh /usr/local/bin/wrapper.sh

ENTRYPOINT ["wrapper.sh"]
CMD ["postgres", "--port=5432"]